USE [master]
GO
/****** Object:  Database [Campus]    Script Date: 10/09/2018 14:11:18 ******/
CREATE DATABASE [Campus] ON  PRIMARY 
( NAME = N'Campus', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Campus.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Campus_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Campus_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Campus] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Campus].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Campus] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Campus] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Campus] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Campus] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Campus] SET ARITHABORT OFF
GO
ALTER DATABASE [Campus] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Campus] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Campus] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Campus] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Campus] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Campus] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Campus] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Campus] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Campus] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Campus] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Campus] SET  DISABLE_BROKER
GO
ALTER DATABASE [Campus] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Campus] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Campus] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Campus] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Campus] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Campus] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Campus] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Campus] SET  READ_WRITE
GO
ALTER DATABASE [Campus] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Campus] SET  MULTI_USER
GO
ALTER DATABASE [Campus] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Campus] SET DB_CHAINING OFF
GO
USE [Campus]
GO
/****** Object:  Table [dbo].[Role]    Script Date: 10/09/2018 14:11:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Role] ON
INSERT [dbo].[Role] ([Id], [Name]) VALUES (1, N'管理员')
INSERT [dbo].[Role] ([Id], [Name]) VALUES (2, N'老师')
INSERT [dbo].[Role] ([Id], [Name]) VALUES (3, N'学生')
SET IDENTITY_INSERT [dbo].[Role] OFF
/****** Object:  Table [dbo].[HomeWork]    Script Date: 10/09/2018 14:11:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HomeWork](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](100) NOT NULL,
	[Content] [ntext] NOT NULL,
	[AuthorId] [int] NULL,
	[ReleaseTime] [datetime] NULL,
	[Deleted] [bit] NOT NULL,
 CONSTRAINT [PK__HomeWork__3214EC070EA330E9] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 10/09/2018 14:11:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](20) NOT NULL,
	[Password] [nvarchar](20) NOT NULL,
	[RoleId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UserName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Answer]    Script Date: 10/09/2018 14:11:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Answer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Content] [ntext] NOT NULL,
	[AuthorId] [int] NOT NULL,
	[ReleaseTime] [datetime] NULL,
	[HomeworkId] [int] NOT NULL,
	[Deleted] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Default [DF_HomeWork_Deleted]    Script Date: 10/09/2018 14:11:19 ******/
ALTER TABLE [dbo].[HomeWork] ADD  CONSTRAINT [DF_HomeWork_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO
/****** Object:  Default [DF_Users_RoleId]    Script Date: 10/09/2018 14:11:19 ******/
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_RoleId]  DEFAULT ((3)) FOR [RoleId]
GO
/****** Object:  Default [DF_Answer_Deleted]    Script Date: 10/09/2018 14:11:19 ******/
ALTER TABLE [dbo].[Answer] ADD  CONSTRAINT [DF_Answer_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO
/****** Object:  ForeignKey [FK__Users__RoleId__0BC6C43E]    Script Date: 10/09/2018 14:11:19 ******/
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role] ([Id])
GO
/****** Object:  ForeignKey [FK__Answer__AuthorId__164452B1]    Script Date: 10/09/2018 14:11:19 ******/
ALTER TABLE [dbo].[Answer]  WITH CHECK ADD FOREIGN KEY([AuthorId])
REFERENCES [dbo].[Users] ([Id])
GO
/****** Object:  ForeignKey [FK__Answer__Homework__173876EA]    Script Date: 10/09/2018 14:11:19 ******/
ALTER TABLE [dbo].[Answer]  WITH CHECK ADD  CONSTRAINT [FK__Answer__Homework__173876EA] FOREIGN KEY([HomeworkId])
REFERENCES [dbo].[HomeWork] ([Id])
GO
ALTER TABLE [dbo].[Answer] CHECK CONSTRAINT [FK__Answer__Homework__173876EA]
GO